<!DOCTYPE html>
<html lang="en">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<link rel="shortcut icon" href="${basePath}/images/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="${basePath}/js/libs/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="${basePath}/css/style.css">
<link rel="stylesheet" type="text/css" href="${basePath}/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="${basePath}/css/responsive.css">
<link rel="stylesheet" type="text/css" href="${basePath}/css/jquery.flipster.css">
<link rel="stylesheet" type="text/css" href="${basePath}/js/libs/fileinput/css/fileinput.css">
<script type="text/javascript" src="${basePath}/js/libs/sea/sea.js" ></script>
<script type="text/javascript" src="${basePath}/js/libs/jquery/jquery.js" ></script>
<script type="text/javascript" src="${basePath}/js/libs/bootstrap/js/bootstrap.min.js" ></script>

<head>
		<title>
				<c:out value="${PAGE_TITLE}"/> 
		</title>
</head>  
<body>