<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:set var="basePath" value="${pageContext.request.contextPath}" /> 
<link rel="shortcut icon" href="${basePath}/images/favicon.ico" type="image/x-icon" />
<link href="${basePath}/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="${basePath}/css/font-awesome.min.css" rel="stylesheet">
<link href="${basePath}/css/style.css" rel="stylesheet">
